const OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1';

export interface AnalysisResult {
	isAiGenerated: boolean;
	confidence: number;
	reasoning: string;
	details: {
		artifacts: string[];
		naturalElements: string[];
	};
}

export async function analyzeWithVision(
	apiKey: string,
	base64Image: string,
	mimeType: string,
	context: 'image' | 'video_frame' | 'website_screenshot'
): Promise<AnalysisResult> {
	const contextPrompts: Record<string, string> = {
		image: 'Analyze this image and determine if it was generated by AI (e.g., Midjourney, DALL-E, Stable Diffusion, Flux) or is a real photograph/artwork.',
		video_frame: 'This is a frame extracted from a video. Analyze it and determine if the video was generated by AI (e.g., Sora, Runway, Kling, Pika).',
		website_screenshot: 'This is a screenshot of a website. Analyze visible images and content to determine if they appear to be AI-generated.'
	};

	const systemPrompt = `You are an expert forensic AI/deepfake content detector. You MUST classify ANY image that has been manipulated by AI as AI-generated. This includes:
- Fully AI-generated images (Midjourney, DALL-E, Stable Diffusion, Flux)
- Face swaps and deepfakes (FaceSwap, DeepFaceLab, Reface, InsightFace)
- AI-enhanced or AI-modified photos (AI upscaling, AI face editing, AI background replacement)
- AI face filters and beauty filters that significantly alter appearance
- AI-animated faces (D-ID, HeyGen, Synthesia)

ALL of these count as "AI-generated" for our purposes. If AI was involved in creating or significantly modifying the image, isAiGenerated MUST be true.

DETECTION CHECKLIST — check ALL of these:

FACE SWAP / DEEPFAKE indicators:
- Face that doesn't match the body (skin tone mismatch, neck seam, different lighting on face vs body)
- Face edges that blur or blend unnaturally into surrounding skin/hair
- Inconsistent skin texture between face and rest of body
- Facial features that look "pasted on" or floating
- Mismatched resolution between face and background
- Unnatural face-to-head proportions
- Hair that clips through or blends weirdly at face boundaries
- Face that looks like a known person transplanted onto different body

FULL AI GENERATION indicators:
- Hands with wrong finger count, fused fingers, or odd proportions
- Warped, morphing, or impossible background geometry
- Garbled or nonsensical text/letters
- Too-perfect skin, overly smooth or waxy appearance
- Eyes that don't match (different size, focus, or reflections)
- Uncanny valley feeling
- Stylistic patterns of specific AI models

SIGNS OF AUTHENTIC (unmodified) content:
- Natural sensor noise consistent across ENTIRE image (face AND body AND background)
- Consistent lighting, resolution, and compression across all parts of image
- Natural skin imperfections everywhere (not just body but face too)
- No visible seams or blending boundaries

IMPORTANT: When in doubt, flag as AI-generated. A face swap IS AI-generated content.

Respond ONLY with valid JSON:
{
  "isAiGenerated": true/false,
  "confidence": 0.0-1.0,
  "reasoning": "Brief explanation",
  "details": {
    "artifacts": ["specific AI/deepfake artifacts found"],
    "naturalElements": ["specific authentic elements found"]
  }
}`;

	const response = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
		method: 'POST',
		headers: {
			'Authorization': `Bearer ${apiKey}`,
			'Content-Type': 'application/json',
			'HTTP-Referer': 'https://isthisai.app',
			'X-Title': 'IsThisAI'
		},
		body: JSON.stringify({
			model: 'anthropic/claude-sonnet-4',
			messages: [
				{ role: 'system', content: systemPrompt },
				{
					role: 'user',
					content: [
						{ type: 'text', text: contextPrompts[context] },
						{
							type: 'image_url',
							image_url: {
								url: `data:${mimeType};base64,${base64Image}`
							}
						}
					]
				}
			],
			temperature: 0.1,
			max_tokens: 1024
		})
	});

	if (!response.ok) {
		const err = await response.text();
		throw new Error(`OpenRouter API error: ${response.status} - ${err}`);
	}

	const data = await response.json();
	const content = data.choices[0]?.message?.content;
	if (!content) throw new Error('No response from model');

	const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/) || [null, content];
	return JSON.parse(jsonMatch[1].trim()) as AnalysisResult;
}

export async function analyzeText(apiKey: string, text: string): Promise<AnalysisResult> {
	const systemPrompt = `You are an expert AI text detector. Your job is to analyze text and determine if it was written by AI (e.g., ChatGPT, Claude, Gemini) or by a human.

Look for these AI writing patterns:
- Overly structured and organized formatting
- Generic or vague statements that lack specificity
- Excessive use of transitional phrases
- Unnaturally consistent tone throughout
- Formulaic paragraph structure
- Overuse of certain phrases ("It's important to note", "In conclusion", "delve", "landscape")
- Lack of personal anecdotes or unique perspectives
- Perfect grammar with no colloquialisms
- Tendency to be balanced/neutral on controversial topics
- Lists that are too neatly organized

Also look for signs of human writing:
- Personal voice and unique style
- Colloquial language and slang
- Minor grammatical imperfections
- Emotional language and strong opinions
- Specific personal experiences or references
- Inconsistent formatting
- Stream-of-consciousness elements

Respond ONLY with valid JSON in this exact format:
{
  "isAiGenerated": true/false,
  "confidence": 0.0-1.0,
  "reasoning": "Brief explanation of your analysis",
  "details": {
    "artifacts": ["list of AI writing patterns found"],
    "naturalElements": ["list of human writing elements found"]
  }
}`;

	const response = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
		method: 'POST',
		headers: {
			'Authorization': `Bearer ${apiKey}`,
			'Content-Type': 'application/json',
			'HTTP-Referer': 'https://isthisai.app',
			'X-Title': 'IsThisAI'
		},
		body: JSON.stringify({
			model: 'anthropic/claude-sonnet-4',
			messages: [
				{ role: 'system', content: systemPrompt },
				{
					role: 'user',
					content: `Analyze this text and determine if it was written by AI or a human:\n\n---\n${text}\n---`
				}
			],
			temperature: 0.1,
			max_tokens: 1024
		})
	});

	if (!response.ok) {
		const err = await response.text();
		throw new Error(`OpenRouter API error: ${response.status} - ${err}`);
	}

	const data = await response.json();
	const content = data.choices[0]?.message?.content;
	if (!content) throw new Error('No response from model');

	const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/) || [null, content];
	return JSON.parse(jsonMatch[1].trim()) as AnalysisResult;
}
